cheapreats/react-ui-library

package-lock.json
package.json
src/components/buttons/Button.js
src/components/inputs/Input.js
src/components/texts/HeadingOne.js
src/components/texts/HeadingThree.js
src/components/texts/HeadingTwo.js
src/components/texts/Paragraph.js
src/components/variables.js
src/stories/button.js

- **Added icon attribute to button**
- Described within the storyboard
- **Changed proptypes to be node instead of text**
- This allows us to do things like add anchors and icons within text without issues

[CHEAP-443] - Button changes

---

.storybook/config.js
src/components/buttons/Button.js
src/components/inputs/Input.js
src/stories/Overview.js
src/stories/button.js
src/stories/components/Overview.js

*DONE*
- Buttons are a tiny bit bigger (by 1px if you're that curious)
- Takes a size parameter which would scale the button proportionally (ie. paddings scales with it)
- Touched up input a tiny bit to fix spacing issues 
- Added H4 and H5 to the page and overview
- Fixed typo in overview
- Added herobine

Added extra functionality for terminal use

---

package-lock.json
package.json
src/components/buttons/Button.js
src/components/inputs/Input.js
src/components/texts/Link.js
src/stories/Link.js
src/stories/button.js
src/stories/input.js

*DONE*
- Added black attribute for button
- Updated link to have dotted line
- Non-primary button has interactions

Changes for dashboard

---

.storybook/config.js
package-lock.json
package.json
src/components/containers/Buttons.js
src/components/index.js
src/components/inputs/Input.js
src/components/inputs/Select.js
src/components/inputs/TimePicker.js
src/stories/Button.js
src/stories/Select.js
src/stories/TimePicker.js
webpack.config.js

- Added Timepicker
- Fixed webpack with css
- Fixed static sizing of select
- Made button wrapper to be more dynamic

[CHEAP-447+] - Fixes for components and more

---

package-lock.json
package.json
src/components/inputs/Select.js
src/components/inputs/TimePicker.js
src/stories/Select.js

- Fixed weird overlapping with other components
- Changed onChange return to simulate an 'event'
- Added hasNull property to options

[CHEAP-491] - Fixes for timepicker

---

package-lock.json
package.json
src/components/inputs/Tag.js

- Fixed issue where dashboard crashes when icon is clicked

[CHEAP-513] - updated packages and fixed icon click for tag issue

---

src/components/containers/Footnote.js

- Footnote isn't as intrusive in positioning
- Footnote now transitions properly

Fixed footnote

---

.storybook/config.js
package-lock.json
package.json
src/components/containers/Card.js
src/components/containers/Footnote.js
src/components/index.js
src/components/inputs/Checkbox.js
src/components/layout/Column.js
src/components/layout/Row.js
src/stories/Card.js
src/stories/Grid.js

- Created 12 column grid system
- Added card

Two new components :D

---

src/Containers/Card.tsx
src/Containers/index.ts
src/Themes/ThemeTemplate.ts
stories/Containers/Card.stories.js

[HTV4-29] Create Card component

---

src/Containers/Footnote.tsx
src/Containers/index.ts
stories/Containers/Footnote.stories.js

https://wolfbeacon.atlassian.net/browse/HTV4-27

Finished Footnote

---

src/Inputs/Textarea.tsx
src/Inputs/index.ts
stories/Inputs/Textarea.stories.js

@fpunny please add in the automatic textarea resize. thanks

Started Textarea component

---

package.json
src/Inputs/Image.tsx
stories/Inputs/Image.stories.js

Fixed bug where the wrong part of the cropped image was being returned in the upload button.

Upload Button - fix bug

---

package-lock.json
package.json
src/Containers/Tag.tsx
src/Inputs/Datepicker/Datebox.tsx
src/Inputs/Datepicker/index.tsx
src/Inputs/ExcelOptions.tsx
src/Inputs/index.ts
stories/Inputs/ExcelOptions.stories.js

Build Excel Options component as per design: https://wolfbeacon.atlassian.net/wiki/spaces/CW/pages/1018789892/Excel+Download+Options+Component
Had to edit some logic in Date Picker component to allow for Datepicker to render without a default value.

Excel Options Component

---

src/Inputs/Datepicker/Datebox.tsx
src/Inputs/Datepicker/index.tsx
src/Inputs/ExcelOptions.tsx
stories/Inputs/ExcelOptions.stories.js

Fix bug with headers and Datepicker. In Datepicker if no date was selected the calendar would not scroll between months properly. In ExcelOptions Component the onChange (in the Select which shows available headers to choose from) would update the state with an incorrect key. Also, updated the UI for the component and added proper headers/descriptions

ExcelOptions Component bug fix

---

package.json
src/Inputs/Image.tsx
stories/Inputs/Image.stories.js

Fixed issue where the Image component was returning the URL of the blob rather than the base64 data

Image Upload Button

---

package.json

Forgot to update version number...

Update Version Number

---

package-lock.json
package.json
src/Inputs/EmojiPicker.tsx
src/Inputs/index.ts
stories/Inputs/EmojiPicker.stories.js

A component that will allow a vendor to pick an emoji to use with their loyalty program.

Emoji Picker

---

package.json
src/Inputs/Image.tsx

Fixed bug where the same image could not be uploaded twice in a row. The value for the input element had to be set to null between file selection.

Fix bug for Image Uploader

---

.storybook/addons.ts
package-lock.json
package.json
src/Containers/Navigation.tsx
stories/Containers/Navigation.stories.js

Updated Navigation component to allow a footer prop to be passed into it.

CEENG-253 Allow footer to passed into Navigation

---

package.json
src/Containers/NavigationFootnote.tsx
src/Containers/index.ts
stories/Containers/Navigation.stories.js
stories/Containers/NavigationFootnote.stories.js

Created a Navigation Footer component as it is reused by Dashboard and Terminal

CEENG-255 Navigation Footer

---

src/Containers/ImageCarousel.tsx
src/Containers/index.ts
stories/Containers/ImageCarousel.stories.js

Added Image Carousel Component

CEENG 222 UI

---

package.json
src/Inputs/Checkbox.tsx

Added null check to fix checkbox error which appears in the live version of the dashboard v2

CEENG-261 Checkbox Error

---

src/Containers/Card.tsx
src/Containers/Footnote.tsx
src/Text/Heading.tsx
src/Text/SmallText.tsx

@ralph-dev 
@nikitasheremet 
Add type to the props for react UI for Heading component.

Terminal v2 ts fixes

---

package.json
src/Inputs/Datepicker/index.tsx

Added value as dependency in Use Effect, and added setText to useEffect

CEENG-326 Update Datepicker to Fix Bug

---

package-lock.json
src/Containers/PictureCard.tsx
src/Containers/index.ts
stories/Containers/PictureCard.stories.js

added PictureCard component to the library

---

src/Inputs/SearchBar.tsx
src/Inputs/index.ts
stories/Inputs/SearchBar.stories.js

added searchbar to the library

---

src/Containers/FeaturesCard.tsx
src/Containers/index.ts
stories/Containers/FeaturesCard.stories.js

Added Features Card

---

src/Containers/SlidingOutPanels.tsx
src/Containers/index.ts
stories/Containers/SlidingOutPanels.stories.js

- The cards are stacked one upon the other
- Uses animation and keyframes to cause the sliding and effect
[See Jira ticket for more details](https://wolfbeacon.atlassian.net/browse/CEM-401)

CEM-401 Created Sliding out panels

---

src/Containers/SelectList.tsx
src/Containers/index.ts
src/Inputs/ComboBox.tsx
src/Inputs/CustomSearch.tsx
src/Inputs/SearchBar.tsx
src/Inputs/Select.tsx
src/Inputs/index.ts
stories/Inputs/ComboBox.stories.js
stories/Inputs/CustomSearch.stories.js
stories/Inputs/SearchBar.stories.js

added CustomSearch Component to the Library

---

.vscode/settings.json
package-lock.json
package.json
src/Containers/FeaturesCard.tsx
src/Containers/HorizontalScrollList.tsx
src/Containers/List.tsx
src/Containers/SelectList.tsx
src/Containers/SlidingOutPanels.tsx
src/Containers/index.ts
src/Inputs/ComboBox.tsx
src/Inputs/MutliSelect/MultiSelectItem.tsx
src/Inputs/SearchBar.tsx
src/Inputs/Select.tsx
stories/Containers/HorizontalScrollList.stories.js

CEM-347 horizontal scroll list

---

.storybook/config.js
src/Containers/ClientShowCase/ClientShowCase.tsx
src/Containers/ColorCard.tsx
src/Containers/index.ts
stories/Overview/Typography.stories.js
stories/Overview/index.stories.js

-Added stories for typography and color
-Added sorting to the stories so Overview shows at the top
-Added ColorCard component similar to the one on the master branch

Overview Stories

---

src/Inputs/MaskedInput.tsx
stories/Inputs/MaskedInput.stories.js

masked input responsive on mask change

---

src/Containers/List.tsx

-changed props to be optional as they should be (shown in stories)
-fixed footer/header ts errors

fix list ts errors

---

package-lock.json
package.json
src/Containers/ImageCarousel.tsx
src/Containers/NavigationFootnote.tsx
src/Containers/Settings/AccountCard.tsx
src/Containers/Settings/InfoCard.tsx
src/Containers/Tag.tsx
src/Inputs/Button.tsx
src/Inputs/Checkbox.tsx
src/Inputs/Datepicker/Datebox.tsx
src/Inputs/Datepicker/index.tsx
src/Inputs/Image.tsx
src/Inputs/SearchBar.tsx
src/Inputs/Select.tsx
src/Inputs/Timepicker/TimeDisplay.tsx
stories/Containers/FeaturesCard.stories.js
stories/Containers/HorizontalStoreCard.stories.js
stories/Containers/PictureCard.stories.js
stories/Containers/StoreFeatureCard.stories.js
stories/Containers/Tag.stories.js
stories/Inputs/Button.stories.js

- fix pathing issues that arise when upgraded versions are used as well

Styled icon and styled-component package version upgrade

---

src/Containers/ClientShowCase/ClientShowCase.tsx
src/Containers/ClientShowCase/ClientShowCaseItem.tsx
src/Containers/HorizontalScrollList.tsx
src/Containers/ImageCarousel.tsx
src/Containers/NavigationFootnote.tsx
src/Containers/RankingTable.tsx
src/Containers/Settings/AccountCard.tsx
src/Containers/Settings/InfoCard.tsx
src/Containers/index.ts
src/Inputs/Checkbox.tsx
src/Inputs/ColorPicker.tsx
src/Inputs/ComboBox.tsx
src/Themes/MainTheme.ts
stories/Containers/ImageCarousel.stories.js
stories/Containers/RankingTable.stories.js

Created styled Ranking Component with sorting and filtering functionality for the total spent. Also added it to storybook and tested with different volumes of data.
@ralph-dev

CEM-757_Ranking_Component

---

src/Containers/RankingTable.tsx

Importing all Mixins from mixin index in the Ranking Component
@indancisive

Import all mixins from Mixins

---

src/Containers/DiningReservation.tsx
stories/Containers/DiningReservation.stories.js
stories/Containers/ImageCarousel.stories.js

Created the dining reservation component, added the create booking and confirm booking button

CEM-823-Dining-Reservation-Component

---

src/Containers/HeaderRow.tsx
src/Containers/KitchenCard/KitchenCard.tsx
src/Containers/KitchenCard/KitchenCardItems.tsx
src/Containers/KitchenCard/index.ts
src/Containers/Status.tsx
src/Containers/index.ts
src/Themes/MainTheme.ts
stories/Containers/HeaderRow.stories.js
stories/Containers/KitchenCard.stories.js
stories/Containers/Status.stories.js

Added components and stories for Status, KitchenCard, and HeaderRow.

CEM-845-KitchenCard-Component

---

package-lock.json

Commited the changed to package.json directly to v2.

bump-version-number-2.3.40

---

src/Containers/Settings/AccountCard.tsx
src/Containers/Settings/InfoCard.tsx
src/Containers/Settings/index.tsx

CEM-855 Added Props

---

package-lock.json
package.json

bump-version-number-2.3.41

---

src/Containers/HeaderRow.tsx
src/Containers/ImageCarousel.tsx
src/Containers/KitchenCard/KitchenCard.tsx
src/Containers/KitchenCard/KitchenCardItems.tsx
src/Containers/KitchenCard/index.ts
src/Containers/Settings/AccountCard.tsx
src/Containers/Settings/InfoCard.tsx
src/Containers/Settings/index.tsx
src/Containers/Status.tsx
src/Themes/MainTheme.ts
stories/Containers/HeaderRow.stories.js
stories/Containers/KitchenCard.stories.js
stories/Containers/Status.stories.js

-make props optional in image carousel
-prettier changes
-remove repeated const name
-change prop name of order_type to camel case in kitchen card

Fix image carousel and some miscellaneous other ts errors in the ui library

---

package.json

bump-version-number-2.3.44

---

package.json

bump-version-number-2.3.45

---

package.json

bump-version-number-2.3.46

---

src/Containers/SettingsCard.tsx
stories/Containers/ImageCarousel.stories.js
stories/Containers/SettingsCard.stories.js

The terminal has this as a component even though it is in the library. Updated SettingsCard to have onClick mouseEvent and added conditional cursor when icon is clickable.
Removed unneccessary import ImageCarouselStories.

CEM-949-Settings-Card-Component

---

src/Containers/DisplayItem.tsx
src/Containers/Settings/AccountCard.tsx
src/Containers/index.ts
stories/Containers/DisplayItem.stories.js

Adding component to library from terminal/AccountCard

CEM-950 DisplayItem Component

---

package.json

bump version number 2.3.47

---

package.json

bump-version-number-2.3.48 

---

src/Containers/QRScan.tsx
src/Containers/index.ts
stories/Containers/QRScan.stories.tsx

make a QRScan component in storybook

V2 roggc - QRScan Component

---

stories/Containers/SlidingOutPanels.stories.tsx

Sliding Out Panels

---

src/Containers/Coupon.tsx
src/Containers/index.ts
stories/Containers/Coupon.stories.tsx

Create a Coupon component on Storybook

Coupon Component

---

src/Containers/KitchenCard/KitchenCard.tsx
src/Containers/Status.tsx
src/Themes/MainTheme.ts
src/Themes/ThemeTemplate.ts
stories/Containers/Status.stories.tsx

Renamed StatusColors to green red orange.
Updated prop name to statusColor.
Added Ipad Pro view width to theme media.

CEM-1023 Status theme and Ipad Pro mixin

---

.babelrc
.eslintrc.js
package-lock.json
package.json
src/Containers/Chart.tsx
src/Containers/index.ts
stories/Containers/Chart.stories.tsx

Make a chart component with recharts library.

Chart Component

---

src/Containers/Chart.tsx
src/Containers/Stock.tsx
src/Containers/index.ts
stories/Containers/Stock.stories.tsx

stock component

---

package-lock.json
package.json

Version was bumped in Force Deploy to Server, but not published. Will publish this version.
Moved storybook dependancies to devdependancies to solve issue of react detecting higher version of webpack when used in applications.

bump version number to 2.3.50

---

src/Containers/List/List.tsx
src/Containers/List/ListFooter.tsx
src/Containers/List/ListHeader.tsx
src/Containers/List/ListItem.tsx
src/Containers/List/ListToggle.tsx
src/Containers/Navigation.tsx
stories/Containers/List.stories.tsx

ListHeader and ListFooter padding as optional props.
Changed isSelected background color to same shade as onHover.
Setting display of ListToggle as a styled higher order component does not work as intended. Added logic to hide the toggle on responsive.
Added zindex and padding props to Navigation

CEM-1063 Update List and Navigation

---

src/Themes/ThemeTemplate.ts

to solve a bug in the dashboard project, the logo is not seen properly

CEM-1184 Change url logo in theme

---

package.json

bump version number to 2.3.52

---

src/Inputs/MaskedInput.tsx

Masked Input handles negative values.
Better handling of display and real value when typing input. Previous had to unfocus to change value.
Removed Magic Strings.
Added Regex for input validation.
Made min and max optional.

CEM-1187 Masked Input Fix

---

src/Containers/Landing.tsx
src/Containers/index.ts
stories/Containers/Landing.stories.tsx

Landing Component from Terminal and Dashboard.
Smalltext opacity 0.7 is odd for coloring, but it is the same method Info in LabelLayout uses, which is used by Input components.

CEM-1189 Landing Component

---

src/Containers/WarningCard.tsx
src/Containers/index.ts
stories/Containers/WarningCard.stories.tsx

Dashboard has two instances of WarningCard component.
Adding to React-UI library as it may have use cases in future and removes code from Dashboard.

CEM-1232 Warning Component

---

src/Utils/Hooks/index.ts
src/Utils/Hooks/useMounted.ts

useMounted to React-UI library

CEM-1216-useMounted

---

src/Inputs/Image.tsx
stories/Inputs/Image.stories.tsx

This component did not function as intended. When cropping an image it would give you a distorted image that was off centered and did not return the correct crop.
Now the component returns the correctly cropped base64 image.

CEM-1239-Image-Component-Croping

---

package.json

bump-version-to-2.3.56

---

package.json

bump-version-to-2.3.57

---

package-lock.json
package.json
src/Inputs/MaskedInput.tsx

MaskedInput now handles floats and numbers with decimals.

CEM-1255 Masked Input Float

---

src/Inputs/SegmentedButton.tsx
src/Inputs/index.ts
stories/Inputs/SegmentedButton.stories.tsx

A segmented button that takes an array of segment types and creates a row of buttons.

CEM-773 SegmentedButton

---

src/Containers/ReportIssue.tsx
stories/Containers/ReportIssue.stories.tsx

Add report component with custom functionality to add report options and to handle submit event

Add Report Component

---

src/Containers/VendorsList/Profile.tsx
src/Containers/VendorsList/VendorsHeader.tsx
src/Containers/VendorsList/VendorsTable.tsx
src/Containers/VendorsList/index.ts
stories/Containers/VendorsTable.stories.tsx

Bigger pull request than I anticipated, so I'll get an approval on this molecule and move on to the table.

CEM-1291 Email, name, profile molecule

---

src/Containers/CollapsibleHeading/CollapsibleHeading.tsx
src/Containers/CollapsibleHeading/FilterSelect.tsx
src/Containers/VendorsList/VendorsFilter.stories.tsx
src/Containers/VendorsList/VendorsFilter.tsx
src/Containers/VendorsList/index.ts

Actual filtering using react-table will be done with the template.

CEM-1290-Filters-Bar-Organism

---

.eslintrc.js
src/Containers/Chair/Chair.tsx
src/Containers/CircleTable/CircleTable.tsx
src/Containers/ReactTable/PageSelector.tsx
src/Containers/ReactTable/Pagination.tsx
src/Containers/ReactTable/RowSelector.tsx
src/Containers/ReportIssue/ReportIssue.tsx
src/Containers/SquareTable/_ChairRow.tsx
src/Containers/TransactionList/TransactionList.stories.tsx
src/Containers/TransactionList/TransactionList.tsx
src/Containers/index.ts
src/Inputs/EmojiPicker/EmojiPicker.tsx
src/Inputs/ExcelOptions/ExcelOptions.tsx
src/Inputs/Image/Image.tsx
src/Utils/BaseStyles/Main.ts
src/Utils/FormatDate.ts
src/Utils/Mixins/flex.ts

Not quite sure what the target of this was. Made it more dynamic.
https://wolfbeacon.atlassian.net/jira/software/projects/CEM/boards/6?selectedIssue=CEM-767
I see this video, it looks like it is being controlled by the arrow keys?
How it's working currently is very different. Is it supposed to be a scrollable and onHover do an animation?

CEM-767-Transaction

---

package-lock.json
package.json
src/Containers/SignUpPopup/SignUpPopup.stories.tsx
src/Containers/SignUpPopup/SignUpPopup.tsx

Pop up that if a user ignores it, the cookie will expire in 30 days, but if the user subscribes, it will expire in one year.

CEM-1476 Simple Signup Popup

---

src/Containers/SignUpPopup/SignUpPopup.stories.tsx
src/Containers/SignUpPopup/SignUpPopup.tsx
src/Containers/index.ts

Export pop up from containers index

Fix Export

---

src/Containers/ProfileCard/ProfileCard.tsx
src/Containers/VisitNotification/VisitNotification.stories.tsx
src/Containers/VisitNotification/VisitNotification.tsx
src/Containers/index.ts

Add visit notification

---

src/Containers/Chart/Chart.tsx
src/Containers/SignUpPopup/SignUpPopup.tsx

the chart component was causing dashboard to crash, as reported by @Ampatte2 .

CEM-1393 bug in chart component

---

src/Containers/Dropdown/Dropdown.stories.tsx
src/Containers/Dropdown/Dropdown.tsx
src/Containers/Dropdown/DropdownItem.tsx
src/Containers/Dropdown/index.ts

Add dropdown and dropdown item components. Add dropdown button as a prop to the dropdown so the user can choose what element triggers the dropdown.

CEM-1302-Dropdown

---

src/Containers/BoxComposition/BoxComposition.stories.tsx
src/Containers/BoxComposition/BoxComposition.tsx
src/Containers/index.ts
src/Fragments/TextLayout.tsx

do two squares and a rectangle with images that changes coinciding with animation
as you can see the animation of the text and the squares do not coincide in time.

CEM-2045 box composition

---

src/Containers/BoxComposition2/BoxComposition2.stories.tsx
src/Containers/BoxComposition2/BoxComposition2.tsx
src/Containers/index.ts

CEM-2061 box composition 2

---

package.json
src/Containers/ProfileCard/ProfileCard.stories.tsx
src/Containers/ProfileCard/ProfileCard.tsx

set a default image on profilecard component

Cem 2096 default image in profilecard component

---

src/Inputs/SearchBarExpandable/SearchBarExpandable.stories.tsx
src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx
src/Inputs/index.ts

CEM-2131 make an expandable search bar

---

src/Containers/List/List.stories.tsx
src/Containers/List/ListHeader.tsx
src/Inputs/SearchBarExpandable/SearchBarExpandable.stories.tsx
src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx

CEM-2130 add search functionality to ListHeader component in react-ui

---

package.json
src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx

CEM-2170bis clear input on closing and add an onClose property

---

src/Containers/ProfileCard/ProfileCard.tsx

CEM-2175 profilecard issue

---

package.json
src/Fragments/InputFragment.tsx
src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx

CEM-2224 Make some changes to SearchBarExpandable

---

package.json
src/Containers/List/ListHeader.tsx

add margin prop (optional) to ListHeader component

adding margin to ListHeader component

---

package.json
src/Containers/CapacityDisplay/CapacityDisplay.tsx
src/Containers/WaitTimeDisplay/WaitTimeDisplay.tsx

Updated the styles for AverageWaitTime/CurrentCapacityDisplay components to fit with the Management Page for the CheaprEats terminal.

Display updates

---

src/Containers/FeatureDisplay/FeatureDisplay.stories.tsx
src/Containers/FeatureDisplay/FeatureDisplay.tsx
src/Containers/index.ts

CEM-2232 - Added Feature Display Component

---

package.json
src/Containers/NutritionFact/NutritionFact.stories.tsx
src/Containers/NutritionFact/NutritionFact.tsx
src/Containers/index.ts
src/Fragments/InputFragment.tsx

CEM-2350 - create a nutrition fact label component

---

src/Containers/SankeyChart/SankeyChart.stories.tsx
src/Containers/SankeyChart/SankeyChart.tsx
src/Containers/index.ts

CEM-2364 - make a sankey chart component

---

package-lock.json
package.json
src/Containers/HorizontalBarChart/HorizontalBarChart.stories.tsx
src/Containers/HorizontalBarChart/HorizontalBarChart.tsx
src/Containers/SankeyChart/SankeyChart.tsx
src/Containers/index.ts

pay attention to the changes at package.json. recharts has been upgraded. there were three components already broken before upgrading: Modal, Settings and Slider.

CEM-2369- create horizontal bar chart component

---

package.json
src/Containers/EditDraggableCanvas/EditDraggableCanvas.stories.tsx
src/Containers/EditDraggableCanvas/EditDraggableCanvas.tsx
src/Containers/EditDraggableCanvas/_DraggableTable.tsx

Made the positions for tables absolute. This allows the tables to be added on top of each other (stack up) without pushing them down.

Absolute Positioning Fix

---

package.json
src/Containers/FileUpload/FileUpload.stories.tsx
src/Containers/FileUpload/FileUpload.tsx

https://drive.google.com/file/d/1Y37N0EZau_G8RZ27VDjF06MLKDDcgVLD/view?usp=sharing
now setIsUploading, setIsFailure and setIsSuccess functions are passed as props to the component to control the status of uploading (reading) a file content

fix file upload

---

package.json
src/Containers/FileUpload/FileUpload.tsx

now shows name of file being uploaded-read.

fix-fileupload-2

---

package.json
src/Containers/CircleTable/CircleTable.tsx
src/Containers/FileUpload/BottomPanel.tsx
src/Containers/FileUpload/FileUpload.stories.tsx
src/Containers/FileUpload/FileUpload.tsx
src/Containers/FileUpload/worker.js
src/Containers/SquareTable/SquareTable.tsx

The new prop will determine if the table is used in the addTableToolbar. If it is used in the toolbar it will not highlight red when the table is clicked.

Added new prop toolbarUse that will change box-shadow css

---

package.json
src/Containers/StretchableButton/StretchableButton.stories.tsx
src/Containers/StretchableButton/StretchableButton.tsx
src/Containers/index.ts

video: 
https://user-images.githubusercontent.com/63363693/115647898-9aede780-a2f2-11eb-9df8-a29430a50be5.mp4

added StretchableButton

---

src/Containers/InviteComponent/Invite.stories.tsx
src/Containers/InviteComponent/Invite.tsx

args, SmallText & Paragraph fixed, as deleted

---

src/Containers/QuestionMarkHover/QuestionMarkHover.stories.tsx
src/Containers/QuestionMarkHover/QuestionMarkHover.tsx

Created a new react component with a hover feature.

Question Mark Hover React Component

---

src/Containers/LimitedTimeBanner/LimitedTimeBanner.stories.tsx
src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
src/Containers/index.ts
src/Themes/MainTheme.ts

Had to reinstall GitHub and VSC for some reason but I finally got the branch published.

CEM 2517 limited time banner

---

src/Containers/CRMTable/CRMTable.stories.tsx
src/Containers/CRMTable/CRMTable.tsx

Modified the CRM Table component adding checkboxes to select specific rows.

GR-CRM CEM-2587 Row Selector

---

src/Inputs/PeopleButton/PeopleButton.stories.tsx
src/Inputs/PeopleButton/PeopleButton.tsx

A button that displays the amount of people and the date of reservation.
Added PeopleButton Component, Files PeopleButton.tsx and PeopleButton.stories.tsx

GR-CEM-2601- Reservation Summary Component

---

src/Containers/ScreenFlashEffect/ScreenFlashEffect.stories.tsx
src/Containers/ScreenFlashEffect/ScreenFlashEffect.tsx
src/Containers/index.ts

https://wolfbeacon.atlassian.net/browse/CEM-2650

roger - CEM-2650 - first version of flash screen effect

---

package.json
src/Containers/Tag/Tag.tsx

Tag improvement

---

src/Containers/PanelCard/PanelCard.stories.tsx
src/Containers/PanelCard/PanelCard.tsx
src/Containers/index.ts
src/Inputs/Button/Button.tsx

roger - no ticket - add PanelCard component

---

src/Containers/PanelListWrapper/PanelListWrapper.stories.tsx
src/Containers/PanelListWrapper/PanelListWrapper.tsx
src/Containers/PanelListWrapper/useFadeOut.ts
src/Containers/PanelListWrapper/useSequentiallyAddedPanels.ts
src/Containers/index.ts

roger- no ticket - create panelListWrapper component

---

src/Containers/DropArea/DropArea.tsx
src/Containers/FileUploadV2/FileUploadV2.stories.tsx
src/Containers/FileUploadV2/FileUploadV2.tsx
src/Containers/FileUploadV2/useInformativePanels.ts
src/Containers/FileUploadV2/worker.ts
src/Containers/PanelCard/PanelCard.tsx
src/Containers/PanelListWrapper/useFadeOut.ts
src/Containers/PanelListWrapper/useSequentiallyAddedPanels.ts
src/Utils/Hooks/index.ts
src/Utils/Hooks/useGetWidth.ts

roger- no ticket- Fileuploadv2final

---

src/Containers/FileUploadV2/FileUploadV2.stories.tsx
src/Containers/RatingBar/RatingBar.stories.tsx
src/Containers/RatingBar/RatingBar.tsx
src/Containers/RatingItem/RatingItem.stories.tsx
src/Containers/RatingItem/RatingItem.tsx
src/Containers/RestaurantReviewCard/RestaurantReviewCard.stories.tsx
src/Containers/RestaurantReviewCard/RestaurantReviewCard.tsx
src/Containers/index.ts
src/Utils/Hooks/useGetWidth.ts

https://wolfbeacon.atlassian.net/browse/CEM-1199

roger- Cem 1199- restaurant review card

---

src/Inputs/ThemeSwitch/ThemeSwitch.stories.tsx
src/Inputs/ThemeSwitch/ThemeSwitch.tsx

CEM-2611 ThemeSwitch
