- src/Inputs/Datepicker/Datebox.tsx
Closes #55
Test Plan:
1. Open Datepicker story
2. Observe that days not in this month are faded
Before:
After:
> [Datepicker] Fix CalendarDay faded prop

- .gitignore
- src/Fragments/InputFragment.tsx
- src/Inputs/MaskedInput.tsx
- src/Inputs/index.ts
- stories/Inputs/MaskedInput.stories.js
Masked input takes in a mask function, and uses abstracted value/onChange handlers to handle events.
```
<MaskedInput
name="demo"
label={text('Enter a value', 'Enter a value')}
placeholder={text('Enter a value', 'Enter a value')}
description={text('Enter a value', 'Enter a value')}
realValue={value}
onRealValueChange={setValue}
mask={s => '$' + s}
/>      
```
There are two preset masks
```
DOLLAR_FORMAT_MASK
PERCENT_FORMAT_MASK
```
there are also no error handling because input already have props to pass-in errors, applications should have its own logic to handle errors (for example you might actually want to enable 120%, I don't want to restrict that, also you might still want to have advanced custom error handling, that cannot be baked into SDK).
**Want approval from all**
> CEENG-263 Add MaskedInput component

- src/Containers/Card.tsx
- src/Containers/Copyright.tsx
- src/Containers/Footnote.tsx
- src/Containers/ImageCarousel.tsx
- src/Containers/List.tsx
- src/Containers/Modal.tsx
- src/Containers/Navigation.tsx
- src/Containers/NavigationFootnote.tsx
- src/Containers/SettingsCard.tsx
- src/Containers/Tag.tsx
- src/Fragments/InputFragment.tsx
- src/Fragments/TextLayout.tsx
- src/Inputs/Button.tsx
- src/Inputs/Checkbox.tsx
- src/Inputs/Datepicker/Datebox.tsx
- src/Inputs/ExcelOptions.tsx
- src/Inputs/MutliSelect/MultiSelect.tsx
- src/Inputs/Radio.tsx
- src/__Layouts/LabelLayout.tsx
- src/__Layouts/TextLayout.tsx
I have updated as many of the components as I could with the HTML attributes. There were some issues where a component uses a "custom" onChange function but because it is also called onChange it throws an error when you try to extend an HTML interface.
> CEENG-312 Update React UI with HTML Attributes

- src/Containers/ImageCarousel.tsx
- stories/Containers/ImageCarousel.stories.js
Modified the ImageCarousel Component to be able to accept additional props to increase flexibility.
ImageCarousel can accept overlay, overlayText, icon, and pointer as props.
> CEM-725-Modify-Image-Carousel-Component

- src/Inputs/Switch.tsx
- stories/Inputs/Switch.stories.js
Modified the switch component to be useable/readable. 
This will break the existing switch useage in EmployeeDetails.tsx and SettingsSwitch in the Terminal.
> CEM-861-Fix-Switch-Component

- src/Containers/KitchenCard/KitchenCard.tsx
- stories/Containers/KitchenCard.stories.js
Modified KitchenCard to accept a component for modifying the status of the order.
Fixed storybook to change order_type to orderType and added story for StatusModifier.
> CEM 909 KitchenCard StatusModifier

- src/Fragments/InputFragment.tsx
- src/Fragments/LabelLayout.tsx
- stories/Inputs/Input.stories.js
Current Implementation of LabelLayout was using a string as a truthy value and for text display. 
The use of useTransition did not result in a transition of the errorLabel when an error value was passed. 
Modified to correct usage of useTransition, added an error message prop to seperate from error.
> CEM-911-Fix-LabelLayout-Error-Display

- .eslintrc.js
- src/Containers/Accordion/Accordion.tsx
- src/Containers/Accordion/AccordionItem.tsx
- src/Containers/DiningReservation.tsx
- src/Containers/ImageCarousel.tsx
- src/Containers/Settings/InfoCard.tsx
- src/Fragments/InputFragment.tsx
- src/Inputs/MaskedInput.tsx
- src/Inputs/Switch.tsx
- src/Inputs/Timepicker/index.tsx
- src/Utils/BaseStyles/Main.ts
- src/Utils/FormatDate.ts
- src/Utils/Mixins/flex.ts
There were warns in a few places about no return type on functions, fixed errors and linted. Modified eslint to not throw error for no-extraneous-dependancies which caused error to be thrown for all imports of fa-solid styled-icons.
> CEM-932-Fix-TypeScript-Errors

- src/Fragments/InputFragment.tsx
- src/Inputs/MaskedInput.tsx
The extension of HTMLAttributes was incorrect and lead to the component not extending the property disabled. Updated input value props to accept InputHTMLAttributes<HTMLInputElement> value props and updated MaskedInput to extend InputHTMLAttributes<HTMLInputElement>.
> CEM-938-Fix-TypeScript-Errors

- src/Containers/Card.tsx
- src/Containers/KitchenCard/KitchenCard.tsx
- src/Containers/KitchenCard/KitchenCardItems.tsx
- src/Inputs/SettingsSwitch.tsx
- src/Inputs/index.ts
- stories/Inputs/SettingsSwitch.stories.js
The orders migration to typescript brought up typing errors with Card since it did not extend main and responsive interfaces.
KitchenCard and KitchenCardItems were incorrectly typed as [ Item ] when it is supposed to be an array of items, Item[ ].
SettingsSwitch is a component in the terminal, adding to library.
> CEM-947-Fix-Typescript-Errors-Orders-Migration

- src/Containers/DisplayItem.tsx
- stories/Containers/DisplayItem.stories.js
In order to accept current terminal implementations of DisplayItem the props are being changed to optional.
> CEM-978 DisplayItem Optional Props

- src/Containers/KitchenCard/KitchenCard.tsx
- src/Containers/KitchenCard/KitchenCardItems.tsx
- src/Containers/KitchenCard/constants.ts
- src/Containers/List/List.tsx
- src/Containers/List/ListHeader.tsx
- src/Containers/List/ListItem.tsx
- src/Containers/List/ListToggle.tsx
- src/Containers/Navigation.tsx
- stories/Containers/List.stories.tsx
- stories/Containers/Stock.stories.tsx
KitchenCard needed stronger typing for the data it was recieving. Added constants to KitchenCard.
List properties have been renamed for clarity, and ListToggle has been made it's own component. 
In ListHeader the option to add a component to the headerRow instead of an Icon has been added.
ListItem has a isSelected prop to indicate that an item is currently selected.
Navigation has an added media query to help with consistent styling of a collapsable list at tablet media query.
> CEM-1054 Add Functionality To List

- src/Fragments/LabelLayout.tsx
LabelLayoutProps description takes in a string originally. However, some components being used in the Cheapreats Dashboard are actually React.Element. Therefore React.Element needed to be added as a type in the description.
> Added React.Element to LabelLayoutProps Description

- .eslintrc.js
- __tests__/utils.test.js
- babel.config.js
- jest.config.js
- package-lock.json
- package.json
- src/Containers/LeftSideBar/CollapsibleHeader.tsx
- src/Containers/LeftSideBar/DraggableElement.tsx
- src/Containers/LeftSideBar/LeftSideBar.tsx
- src/Containers/List/List.tsx
- src/Utils/deepCopy.ts
- stories/Containers/LeftSideBar.stories.tsx
- stories/Inputs/ColorPicker.stories.tsx
- stories/Inputs/ComboBox.stories.tsx
- stories/Inputs/Image.stories.tsx
- stories/Inputs/Input.stories.tsx
- stories/Inputs/Textarea.stories.tsx
- tsconfig.json
deepCopy's previous iteration caused issues in typescript files and did not allow for typed returns.
Now deepCopy returns the the correct typing.
babel.config.js is needed specifically for jest to work.
> CEM-1162 Fix Deep Copy Typing

- src/Containers/Navigation/NavigationItem.tsx
- stories/Containers/Navigation.stories.tsx
NavigationItem did not have exact property. This make that when a link other than home is selected, two links appears with active class, the one selected and home. With this fix then only one link would appear with active class, the one selected.
> CEM-1234 update navigationitem

- src/Inputs/ComboBox.tsx
Previous behavior did not expand options when clicking on the input field. Behavior still is not 100 percent satisfactory.
> CEM-1249 expand options when clicked on input

- src/Inputs/MaskedInput.tsx
- src/Utils/BaseStyles/Main.ts
- src/Utils/FormatDate.ts
- src/Utils/Mixins/flex.ts
- stories/Inputs/MaskedInput.stories.tsx
Reason for this fix, string coersion to number is bad. 
Also, updating onRealValueChange, more consistent to get an event from MaskedInput when dealing with other input elements. Specifically when dealing with external libraries such as formik where you do onRealValueChange={formik.handleChange} rather than having to setFieldValue name, value. This will also prove more extensible in the future.
> CEM-1251 Masked Input Fix

- src/Containers/MiddleCanvas/DualSelectRadio.tsx
- src/Containers/VendorsList/NavigationBar.tsx
- src/Containers/VendorsList/NavigationItem.tsx
- src/Containers/VendorsList/VendorsHeader.tsx
- src/Containers/VendorsList/index.ts
- stories/Containers/VendorsNavigationBar.stories.tsx
I added a responsiveness feature from my last ticket (forgot about it).
Navigation Bar:
Also would it be correct to call this an organism?
> CEM-1286-Vendors-Navigation-Bar-Molecule

- .eslintrc.js
- src/Inputs/MaskedInput.tsx
- stories/Inputs/MaskedInput.stories.tsx
MaskedInput did not support exterior error handling, and for errors to display required a min/max value. Now supports exterior error handling and default error handling.
Phone number mask has been added. Will still error for invalid input, but on blur will now display a formatted phone number with the format 1-xxx-xxx-xxxx.
> CEM-1215-Phone-Number-Mask

- src/Containers/CollapsibleHeading/CollapsibleHeading.stories.tsx
- src/Containers/CollapsibleHeading/CollapsibleHeading.tsx
- src/Containers/CollapsibleHeading/FilterSelect.tsx
- src/Containers/VendorsList/VendorsHeader.tsx
- src/Containers/index.ts
I wanted the collapsible header to be extensible, since for the filtering on the left side there are different child elements in the list. Controls also work, but I didn't show that in the gif.
> Collapsible-Heading-Molecule

- src/Containers/ProfileCard/ProfileCard.tsx
the visitcount in profilecard was positioned absolute which caused to display incorrectly when using in dashboard terminal. adding a position:relative in the parent container should solve the issue (in theory).
> CEM-2085 fix visitcount in profilecard position absolute

- package.json
- src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx
the input field inside SearchBarExpandable had a minimum width which make icon on the right go outside of the box. setting it to 0 solved the problem.
> fixing minwidth in input in searchbar expandable

- src/Containers/List/List.stories.tsx
- src/Containers/List/List.tsx
- src/Containers/List/ListHeader.tsx
- src/Inputs/SearchBarExpandable/SearchBarExpandable.stories.tsx
- src/Inputs/SearchBarExpandable/SearchBarExpandable.tsx
Interesting way to implement this.
Added transitions to ListHeader with search bar instead of removing the element from the dom.
The previous implementation for the search bar was a hack. Now searchbar has a width and an additonal media query.
> CEM-2329 Fix Search Bar

- package-lock.json
- package.json
- src/Containers/CarouselTestimonial/CarouselTestimonial.tsx
is necessary to upgrade babel-plugin-recharts to last version (2.0.0) in order to storybook load properly (this is because we upgraded to last version of recharts previously)
> upgrade babel-plugin-recharts

- package.json
- src/Containers/InviteComponent/Invite.stories.tsx
- src/Containers/InviteComponent/Invite.tsx
I started from Brian's InviteComponent branch (which includes the code in his open PR that Ralph already approved #359).
My changes were: 
Bumped the version number in package.json.
Invite.tsx:
Any other changes you see below were already included in Brian's PR #359.
This should solve the issue. The Invite component is working correctly in Storybook on my end, and the npm tests all cleared.
Let me know if you have any questions.
> Invite component error fix

- src/Containers/TagGroup/TagGroup.tsx
Modified the tag group component to be responsive, as well as implementing a fade effect so the user knows to scroll through the tags when applicable.
> CEM-2582 Responsive Tags

- src/Containers/HighlightedText/HighlightedText.stories.tsx
- src/Containers/HighlightedText/HighlightedText.tsx
When new text is added to labels, the previous text automatically becomes transparent. The 'age' of text can also be overridden to force them to appear as 'old' or 'new'.
> Highlighted Text Part 3
